### ISSUE TITLE
Command module timeout error

### ISSUE THREAD

**Issue by suatozkan** [sorincalin/UiPathTeam.SSHConnector.Activities#1]
Hello, thank you for activity. I want to use this module for SSH connection to Telco network devices.

Connection module works but Command module does NOT. I get timeout error after using the command module. How can I fixed it? This commands normally work on Putty..

**Comment by sorincalin** [comment]
Hi. Apologies, I rarely enter here so missed this by one year. I can't help you investigate but you can get the source code and debug this in Visual Studio.
